# Generated by Django 3.0.4 on 2020-06-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archives',
            old_name='date_taken',
            new_name='request_date',
        ),
    ]
