# Generated by Django 3.0.4 on 2020-06-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20200601_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archives',
            options={'verbose_name': 'archive', 'verbose_name_plural': 'archives'},
        ),
    ]
