# Generated by Django 3.0.4 on 2020-06-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_auto_20200601_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latlng',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
