# Generated by Django 3.0.8 on 2020-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_auto_20200602_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlng',
            name='confirmation_email',
            field=models.CharField(max_length=255),
        ),
    ]
